fake do it

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,26 +12,28 @@ jobs:
         runs-on: ubuntu-latest
         steps:
             - uses: actions/checkout@v4
-            - name: Use Node.js
-              uses: actions/setup-node@v4
-              with:
-                  node-version-file: '.nvmrc'
-            - name: prepare pnpm
-              run: npm i -g pnpm
-            - name: pnpm i
-              run: pnpm i
+#            - name: Use Node.js
+#              uses: actions/setup-node@v4
+#              with:
+#                  node-version-file: '.nvmrc'
+#            - name: prepare pnpm
+#              run: npm i -g pnpm
+#            - name: pnpm i
+#              run: pnpm i
             - name: test
               id: test
-              run: pnpm test
+              run: |
+                  echo "oh oh the tests failed!"
+                  exit 1
               env:
                   LAPIS_TAG: latest
                   SILO_TAG: latest
-            - name: Upload test results
-              uses: actions/upload-artifact@v4
-              if: always()
-              with:
-                  name: test-results
-                  path: testsets/**/output
+#            - name: Upload test results
+#              uses: actions/upload-artifact@v4
+#              if: always()
+#              with:
+#                  name: test-results
+#                  path: testsets/**/output
             - name: Notify failed build
               uses: jayqi/failed-build-issue-action@v1
               if: failure()
